//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaMasterpiece.WCFServices.SupplyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplyServiceReference.ISupplyServie")]
    public interface ISupplyServie {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplyServie/ListAllSupplyInformation", ReplyAction="http://tempuri.org/ISupplyServie/ListAllSupplyInformationResponse")]
        PizzeriaMasterpiece.DTO.SupplyDTO[] ListAllSupplyInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplyServie/ListAllSupplyInformation", ReplyAction="http://tempuri.org/ISupplyServie/ListAllSupplyInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.SupplyDTO[]> ListAllSupplyInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplyServie/UpdateSupplyInformation", ReplyAction="http://tempuri.org/ISupplyServie/UpdateSupplyInformationResponse")]
        PizzeriaMasterpiece.DTO.SupplyDTO UpdateSupplyInformation(PizzeriaMasterpiece.DTO.SupplyDTO supply);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupplyServie/UpdateSupplyInformation", ReplyAction="http://tempuri.org/ISupplyServie/UpdateSupplyInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.SupplyDTO> UpdateSupplyInformationAsync(PizzeriaMasterpiece.DTO.SupplyDTO supply);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupplyServieChannel : PizzeriaMasterpiece.WCFServices.SupplyServiceReference.ISupplyServie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplyServieClient : System.ServiceModel.ClientBase<PizzeriaMasterpiece.WCFServices.SupplyServiceReference.ISupplyServie>, PizzeriaMasterpiece.WCFServices.SupplyServiceReference.ISupplyServie {
        
        public SupplyServieClient() {
        }
        
        public SupplyServieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplyServieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplyServieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplyServieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzeriaMasterpiece.DTO.SupplyDTO[] ListAllSupplyInformation() {
            return base.Channel.ListAllSupplyInformation();
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.SupplyDTO[]> ListAllSupplyInformationAsync() {
            return base.Channel.ListAllSupplyInformationAsync();
        }
        
        public PizzeriaMasterpiece.DTO.SupplyDTO UpdateSupplyInformation(PizzeriaMasterpiece.DTO.SupplyDTO supply) {
            return base.Channel.UpdateSupplyInformation(supply);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.SupplyDTO> UpdateSupplyInformationAsync(PizzeriaMasterpiece.DTO.SupplyDTO supply) {
            return base.Channel.UpdateSupplyInformationAsync(supply);
        }
    }
}
