//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaMasterpiece.ProductoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://schemas.datacontract.org/2004/07/PizzeriaMasterpiece.Model")]
    [System.SerializableAttribute()]
    public partial class ProductoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoProducto_IdTipoProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoProducto_IdTipoProducto {
            get {
                return this.TipoProducto_IdTipoProductoField;
            }
            set {
                if ((this.TipoProducto_IdTipoProductoField.Equals(value) != true)) {
                    this.TipoProducto_IdTipoProductoField = value;
                    this.RaisePropertyChanged("TipoProducto_IdTipoProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoServiceReference.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetProductInformation", ReplyAction="http://tempuri.org/IProductoService/GetProductInformationResponse")]
        PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO GetProductInformation(int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/GetProductInformation", ReplyAction="http://tempuri.org/IProductoService/GetProductInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO> GetProductInformationAsync(int ProductoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/InsertProductInformation", ReplyAction="http://tempuri.org/IProductoService/InsertProductInformationResponse")]
        PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO InsertProductInformation(PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/InsertProductInformation", ReplyAction="http://tempuri.org/IProductoService/InsertProductInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO> InsertProductInformationAsync(PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListAllProductInformation", ReplyAction="http://tempuri.org/IProductoService/ListAllProductInformationResponse")]
        PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO[] ListAllProductInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListAllProductInformation", ReplyAction="http://tempuri.org/IProductoService/ListAllProductInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO[]> ListAllProductInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : PizzeriaMasterpiece.ProductoServiceReference.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<PizzeriaMasterpiece.ProductoServiceReference.IProductoService>, PizzeriaMasterpiece.ProductoServiceReference.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO GetProductInformation(int ProductoId) {
            return base.Channel.GetProductInformation(ProductoId);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO> GetProductInformationAsync(int ProductoId) {
            return base.Channel.GetProductInformationAsync(ProductoId);
        }
        
        public PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO InsertProductInformation(PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO Producto) {
            return base.Channel.InsertProductInformation(Producto);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO> InsertProductInformationAsync(PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO Producto) {
            return base.Channel.InsertProductInformationAsync(Producto);
        }
        
        public PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO[] ListAllProductInformation() {
            return base.Channel.ListAllProductInformation();
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.ProductoServiceReference.ProductoDTO[]> ListAllProductInformationAsync() {
            return base.Channel.ListAllProductInformationAsync();
        }
    }
}
