//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaMasterpiece.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalleEntity
    {
        public int IdPedidoDetalle { get; set; }
        public int Pedido_IdPedido { get; set; }
        public int Producto_IdProducto { get; set; }
        public Nullable<decimal> PrecioDetalle { get; set; }
    
        public virtual PedidoEntity Pedido { get; set; }
        public virtual ProductoEntity Producto { get; set; }
    }
}
