//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaMasterpiece.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle
    {
        public int IdPedidoDetalle { get; set; }
        public int Pedido_IdPedido { get; set; }
        public int Producto_IdProducto { get; set; }
        public Nullable<decimal> PrecioProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
