//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaMasterpiece.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserInformation", ReplyAction="http://tempuri.org/IUserService/GetUserInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PizzeriaMasterpiece.DTO.UserRegistrationDTO))]
        PizzeriaMasterpiece.DTO.UserDTO GetUserInformation(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserInformation", ReplyAction="http://tempuri.org/IUserService/GetUserInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> GetUserInformationAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertUserInformation", ReplyAction="http://tempuri.org/IUserService/InsertUserInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PizzeriaMasterpiece.DTO.UserRegistrationDTO))]
        PizzeriaMasterpiece.DTO.UserDTO InsertUserInformation(PizzeriaMasterpiece.DTO.UserRegistrationDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertUserInformation", ReplyAction="http://tempuri.org/IUserService/InsertUserInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> InsertUserInformationAsync(PizzeriaMasterpiece.DTO.UserRegistrationDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserInformation", ReplyAction="http://tempuri.org/IUserService/UpdateUserInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PizzeriaMasterpiece.DTO.UserRegistrationDTO))]
        PizzeriaMasterpiece.DTO.UserDTO UpdateUserInformation(PizzeriaMasterpiece.DTO.UserRegistrationDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserInformation", ReplyAction="http://tempuri.org/IUserService/UpdateUserInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> UpdateUserInformationAsync(PizzeriaMasterpiece.DTO.UserRegistrationDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginUserInformation", ReplyAction="http://tempuri.org/IUserService/LoginUserInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PizzeriaMasterpiece.DTO.UserRegistrationDTO))]
        PizzeriaMasterpiece.DTO.UserDTO LoginUserInformation(PizzeriaMasterpiece.DTO.UserLoginDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginUserInformation", ReplyAction="http://tempuri.org/IUserService/LoginUserInformationResponse")]
        System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> LoginUserInformationAsync(PizzeriaMasterpiece.DTO.UserLoginDTO user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : PizzeriaMasterpiece.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<PizzeriaMasterpiece.UserServiceReference.IUserService>, PizzeriaMasterpiece.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzeriaMasterpiece.DTO.UserDTO GetUserInformation(int userId) {
            return base.Channel.GetUserInformation(userId);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> GetUserInformationAsync(int userId) {
            return base.Channel.GetUserInformationAsync(userId);
        }
        
        public PizzeriaMasterpiece.DTO.UserDTO InsertUserInformation(PizzeriaMasterpiece.DTO.UserRegistrationDTO user) {
            return base.Channel.InsertUserInformation(user);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> InsertUserInformationAsync(PizzeriaMasterpiece.DTO.UserRegistrationDTO user) {
            return base.Channel.InsertUserInformationAsync(user);
        }
        
        public PizzeriaMasterpiece.DTO.UserDTO UpdateUserInformation(PizzeriaMasterpiece.DTO.UserRegistrationDTO user) {
            return base.Channel.UpdateUserInformation(user);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> UpdateUserInformationAsync(PizzeriaMasterpiece.DTO.UserRegistrationDTO user) {
            return base.Channel.UpdateUserInformationAsync(user);
        }
        
        public PizzeriaMasterpiece.DTO.UserDTO LoginUserInformation(PizzeriaMasterpiece.DTO.UserLoginDTO user) {
            return base.Channel.LoginUserInformation(user);
        }
        
        public System.Threading.Tasks.Task<PizzeriaMasterpiece.DTO.UserDTO> LoginUserInformationAsync(PizzeriaMasterpiece.DTO.UserLoginDTO user) {
            return base.Channel.LoginUserInformationAsync(user);
        }
    }
}
